artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  #source_URL: https://github.com/dharshanabalajii/pipeline_dataset/raw/refs/heads/main/Chicken-fecal-images.zip
  #local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model/effnet
  base_model_path: artifacts/prepare_base_model/effnet/base_model.keras
  updated_base_model_path: artifacts/prepare_base_model/effnet/base_model_updated.keras

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks/effnet
  tensorboard_root_log_dir: artifacts/prepare_callbacks/effnet/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/effnet/checkpoint_dir/model.keras


training:
  root_dir: artifacts/training/effnet/
  trained_model_path: artifacts/training/effnet/model.keras